name: Checkout, Install Dependencies, and Compile Typescript

on:
  workflow_call:

jobs:
  run-command:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install
          npx tsc --outDir dist