name: Checkout, Install Dependencies, and Compile Typescript

on:
  workflow_call:

jobs:
  checkout-install-compile:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install
          npm install ts-node
          npx tsc --outDir dist
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            ./
