name: Generate Today's Answer

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: ./.github/workflows/install-dependencies.yml

    - name: Generate todays answer
      run: npx ts-node dist/scripts/new-word.js

    - name: Commit and push changes, if necessary
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git add -A
          DATE=$(date '+%Y-%m-%d')
          git commit -m "Automated changes for today's word ($DATE)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}