name: Generate Today's Answer

on: 
  schedule: 
    - cron: '0 23 * * *'

  workflow_dispatch:

jobs:
  generate-todays-answer:
    name: Generate Today's Answer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        npm install
        npm install ts-node
        npx tsc --outDir dist
        ls -R
    
    - name: Generate todays answer
      run: |
        npx ts-node dist/src/scripts/new-word.js

    - name: Commit and push changes, if necessary
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
        else
          git add -A
          DATE=$(date '+%Y-%m-%d')
          git commit -m "Automated changes for today's word ($DATE)"
          git remote set-url origin git@github.com:MugillaGurilla/etymodle.git
          git push origin main
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}