on:
  push:
    branches: ["main"]

jobs:
  run-command:
    runs-on: ubuntu-latest 
    steps: 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install
          npx tsc
          npx tsc --outDir dist