# name: Run All Tests

# on:
#   workflow_call:

# jobs: 
#   run-all-tests:
#     runs-on: ubuntu-latest 
#     steps: 
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '20'
      
#       - name: Install dependencies
#         run: |
#           npm install
#           npm install ts-node
#           npx tsc --outDir dist

#       - name: Run tests
#         run: npx cypress run --config video=false
